name: AI Review
on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  ai_code_review:
    runs-on: self-hosted
    steps:
      - name: Trigger AI Code Reviewing
        run: |
          payload=$(jq -n \
            --arg pr_number "${{ inputs.pr_number }}" \
            --arg secret_token "${{ secrets.token }}" \
            '{pullNumber: $pr_number, secretToken: $secret_token, repositoryName: "GitHub"}')
          curl -X POST http://localhost:8090/review \
          -H "Content-Type: application/json" \
          -d "$payload"
