name: workout-tracking-BE CI

on:
  push:
    branches: ['master', 'uat', 'dev']
  pull_request:
    branches: ['master', 'uat', 'dev']

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      issues: write

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Trigger AI Code Reviewing
        run: |
          payload=$(jq -n \
            --arg pr_number "${{ github.event.pull_request.number }}" \
            --arg secret_token "${{ secrets.GITHUB_TOKEN }}" \
            '{pullNumber: $pr_number, secretToken: $secret_token}')

          # send to AI server
          curl -X POST https://ai-coding-review-homie.onrender.com/review \
            -H "Content-Type: application/json" \
            -d "$payload"

      - name: Install Dependencies
        run: |
          npm install

      # only run setup if it's api-test
      - name: Setup for API Test
        run: npm run setup

      - name: Run API Test
        run: |
          npm run api-test

      - name: Clean up
        run: |
          npm run clean
